### ISSUE TITLE
reward functions

### ISSUE THREAD

**Issue by schmidtj3** [zmzhang2000/trustworthy-alignment#2]
Can you point me to the part of the code base that implements the reward functions described in Equations 5, 6, 7, 8 in the paper?

I would like to understand how these equations are translated into code. Thank  you!

**Comment by zmzhang2000** [comment]
> Can you point me to the part of the code base that implements the reward functions described in Equations 5, 6, 7, 8 in the paper?
> 
> I would like to understand how these equations are translated into code. Thank you!

Eqn 5 and 7 are implemented in [L240-L260 of ppo_trainer.py](https://github.com/zmzhang2000/trustworthy-alignment/blob/main/dschat/rlhf/ppo_trainer.py#L240).

Eqn 6 and 8 are implemented in [compute_rewards() of ppo_trainer.py](https://github.com/zmzhang2000/trustworthy-alignment/blob/main/dschat/rlhf/ppo_trainer.py#L283).

**Comment by schmidtj3** [comment]
Thank you very much !
